name: tweet

# Controls when the action will run.
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [main, master]

jobs:
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Load repo and install R
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master

      # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("dplyr")'
          R -e 'install.packages("rvest")'
          R -e 'install.packages("rtweet")'
          R -e 'install.packages("glue")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("stringr")'
          R -e 'install.packages("here")'

      # send tweet
      - name: Tweet
        run: Rscript tweet.r
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add nuforc/data_raw/archive.csv
          git commit -am "GH ACTION Headlines $(date)"
          git push origin master
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
