name: mufon_scrape

# Controls when the action will run.
on:
  schedule:
    - cron:  '0 13 * * *'
  push:
    branches: [main, master]


jobs:
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("dplyr")'
        R -e 'install.packages("rvest")'
        R -e 'install.packages("rtweet")'
        R -e 'install.packages("glue")'
        R -e 'install.packages("readr")'
    # Run R script
    - name: Scrape
      run: Rscript job.r

 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data_raw/*
        git commit -am "GH ACTION Headlines $(date)"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions

    # send tweet
    - name: Tweet
      env:
        TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: Rscript tweet.r

